added amqp(rabbitmq) default provisioner to score-k8s
score-spec/score-k8s pull request #28
Opened 2024-09-03 16:47 UTC by Gkemhcs

This PR adds the **RabbitMQ(amqp)** provisioner to the default provisioners of score-k8s . Fixes #11 

This was tested with a score file that looks like:

```yaml
apiVersion: score.dev/v1b1
metadata:
  name: pika-python-client
containers:
   pika_client
      image: python
      variables:
        amqp_connection_string : ${resources.amqp1.connection}
resources:
  amqp1:
    type: amqp
    
   
      

```

2024-09-04 08:33 UTC, astromechza commented
@Gkemhcs Do you have an example of the output running in a k8s cluster?

2024-09-04 08:41 UTC, astromechza commented
And once you've signed the DCO and signed your commit, the checks will pass :)

2024-09-04 16:02 UTC, Gkemhcs commented
@astromechza 

Here is the sample score workload for k8s

```yaml
apiVersion: score.dev/v1b1
metadata:
  name: amqp-demo
containers:
   nginx:
      image: nginx
      variables:
        AMQP_CONNECTION_URL : ${resources.amqp1.connection}
resources:
  amqp1:
    type: amqp
 ```
 
 and resources it has deployed into the cluster along with **pvc ,pv** is in below snapshot
 
 
![image](https://github.com/user-attachments/assets/4d9347b2-c048-42cf-b738-dbbbcfdbf821)


and logs of rabbitmq statefulset pod 

![image](https://github.com/user-attachments/assets/7bb5266f-244b-48d9-b611-6c78ef92c945)


here is output you asked for .

2024-09-04 16:51 UTC, astromechza requested changes

2024-09-04 16:51 UTC, astromechza commented on internal/provisioners/default/zz-default.provisioners.yaml
> +    host: {{ .State.service }}
Please align the outputs here with the ones in compose: https://github.com/score-spec/score-compose/blob/293dfaf59852bc19a93bae16d3be41c6d9d55d55/internal/command/default.provisioners.yaml#L302 and the documented outputs `host, port, vhost, username, password`

remove management_port, connection, and make the port an integer :)

The reason we remove management_port from the outputs is that not all amqp implementations have a management port like this, and the resource passed to the workload is only concerned with the pure amqp connection, not with any back-office ui.

The rest of it looks good :)

2024-09-05 04:37 UTC, Gkemhcs commented
@astromechza   ,As you instructed i have removed connection and management port from outputs of amqp provisioner

2024-09-05 10:45 UTC, astromechza approved these changes

2024-09-05 10:46 UTC, merged

2024-09-15 14:41 UTC, mathieu-benoit commented
Thanks @Gkemhcs for you contribution! JFYI: this was one of the last pieces in order to have this sample apps working successfully and by default with both `score-compose` and `score-k8s`: https://medium.com/@mabenoit/what-if-the-azure-samples-aks-store-demo-was-using-score-655c55f1c3dd. Thanks!

2024-09-15 14:45 UTC, Gkemhcs commented
You're welcome! I am glad  that my first contribution helped community.
Looking forward to contribute some more